### ISSUE TITLE
graph data sets

### ISSUE THREAD

**Issue by alanyuchenhou** [alanyuchenhou/elephant#48]
I found a collection of weighted graphs over here: https://toreopsahl.com/datasets/
I didn't find weighted graphs on snap: http://snap.stanford.edu/

**Comment by lbholder** [comment]
Datasets 1, 2 and 12 on the first link look good in terms of size. Looks like about 100K edges.

**Comment by lbholder** [comment]
I see several weighted graphs at http://konect.uni-koblenz.de. Some we are already using, but a few big ones, most where the weight is a rating.

**Comment by yuchenhou** [comment]
![running_time](https://user-images.githubusercontent.com/8304443/31113528-93dfc45e-a7ce-11e7-9968-86ec7f79d655.png)

**Comment by yuchenhou** [comment]
I added the descriptions and references for the two new data sets in the paper.
